/*===========================================================================
    FName C++ declarations exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    Copyright 1998-2013 Epic Games, Inc. All Rights Reserved.
===========================================================================*/
#if !ENUMS_ONLY
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#if !defined(__UDKBASE_NAMES_H__) || defined(NAMES_ONLY)

#ifndef __UDKBASE_NAMES_H__
#define __UDKBASE_NAMES_H__
#endif

#ifndef AUTOGENERATE_NAME
#define DEFINED_NAME_MACRO
#define AUTOGENERATE_NAME(name) extern FName UDKBASE_##name;
#endif


AUTOGENERATE_NAME(AdjustAimError)
AUTOGENERATE_NAME(AnimStopFire)
AUTOGENERATE_NAME(BlockUIInput)
AUTOGENERATE_NAME(BreakApart)
AUTOGENERATE_NAME(BreakApartOnDeath)
AUTOGENERATE_NAME(CheckReset)
AUTOGENERATE_NAME(ClearUIInputBlocks)
AUTOGENERATE_NAME(CreateProjectileLight)
AUTOGENERATE_NAME(DelayedLeaveVehicle)
AUTOGENERATE_NAME(DelayedWarning)
AUTOGENERATE_NAME(EntireBeamVelocity)
AUTOGENERATE_NAME(ExecuteWhatToDoNext)
AUTOGENERATE_NAME(GetBestViewTarget)
AUTOGENERATE_NAME(GetCurrentValue)
AUTOGENERATE_NAME(GetCurrentValueIndex)
AUTOGENERATE_NAME(HoldGameObject)
AUTOGENERATE_NAME(InitializeListElementProviders)
AUTOGENERATE_NAME(IsAimCorrect)
AUTOGENERATE_NAME(JumpOutCheck)
AUTOGENERATE_NAME(LockOnWarning)
AUTOGENERATE_NAME(MayDodgeToMoveTarget)
AUTOGENERATE_NAME(MissedDodge)
AUTOGENERATE_NAME(MonitoredPawnAlert)
AUTOGENERATE_NAME(MorphTargetDestroyed)
AUTOGENERATE_NAME(NotifyAnchorFindingResult)
AUTOGENERATE_NAME(NotReachableBy)
AUTOGENERATE_NAME(Num)
AUTOGENERATE_NAME(OnBaseChainChanged)
AUTOGENERATE_NAME(OnBreakApart)
AUTOGENERATE_NAME(OnEncroach)
AUTOGENERATE_NAME(OnLightFinished)
AUTOGENERATE_NAME(OnPropertyChange)
AUTOGENERATE_NAME(OnTurretStatusChange)
AUTOGENERATE_NAME(PhysicsVolumeChanged)
AUTOGENERATE_NAME(PlayTakeHitEffects)
AUTOGENERATE_NAME(PostInitRigidBody)
AUTOGENERATE_NAME(PreloadTextures)
AUTOGENERATE_NAME(RBPenetrationDestroy)
AUTOGENERATE_NAME(ReceivedHealthChange)
AUTOGENERATE_NAME(ReceiveRunOverWarning)
AUTOGENERATE_NAME(RestorePart)
AUTOGENERATE_NAME(SelfDestruct)
AUTOGENERATE_NAME(SetCurrentValueIndex)
AUTOGENERATE_NAME(SetParticleEffect)
AUTOGENERATE_NAME(SetPosition)
AUTOGENERATE_NAME(ShouldBeFiltered)
AUTOGENERATE_NAME(SpawnVehicle)
AUTOGENERATE_NAME(SpecialJumpCost)
AUTOGENERATE_NAME(SpecifyEndAnchor)
AUTOGENERATE_NAME(StartFeignDeathRecoveryAnim)
AUTOGENERATE_NAME(StoppedFalling)
AUTOGENERATE_NAME(StuckFalling)
AUTOGENERATE_NAME(SuperDesireability)
AUTOGENERATE_NAME(TakeFireDamage)
AUTOGENERATE_NAME(TakeHitBlendedOut)
AUTOGENERATE_NAME(TakeWaterDamage)
AUTOGENERATE_NAME(TickAnim)
AUTOGENERATE_NAME(TimeDJReset)
AUTOGENERATE_NAME(UpdateEyeHeight)
AUTOGENERATE_NAME(UpdateHoverboardDustEffect)
AUTOGENERATE_NAME(WhatToDoNext)

#ifdef DEFINED_NAME_MACRO
#undef DEFINED_NAME_MACRO
#undef AUTOGENERATE_NAME
#endif

#endif	//HEADER_GUARD

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#endif	//	!ENUMS_ONLY

