/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    Copyright 1998-2013 Epic Games, Inc. All Rights Reserved.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif


// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_DUKEGAME_ENUMS
#define INCLUDED_DUKEGAME_ENUMS 1


#endif // !INCLUDED_DUKEGAME_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern FName DUKEGAME_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

#ifndef NAMES_ONLY

#ifndef INCLUDED_DUKEGAME_CLASSES
#define INCLUDED_DUKEGAME_CLASSES 1

#endif // !INCLUDED_DUKEGAME_CLASSES
#endif // !NAMES_ONLY

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef DUKEGAME_NATIVE_DEFS
#define DUKEGAME_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_DUKEGAME \

#endif // DUKEGAME_NATIVE_DEFS

#ifdef NATIVES_ONLY

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
